### ISSUE TITLE
请问能给一下在高通骁龙8 Elite平台上推理的示例吗？

### ISSUE THREAD

**Issue by robin-programmer** [THUDM/GLM-Edge#1]
### System Info / 系統信息

无

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
这部分由于我无法拿到对应的来自高通的开源工具包，因此，我们也没办法将对应属于高通的工具包进行开源

**Comment by YangWang92** [comment]
> 这部分由于我无法拿到对应的来自高通的开源工具包，因此，我们也没办法将对应属于高通的工具包进行开源

It seems that running models on QNN doesn't require the "open-source" Qualcomm toolkit, right?
