### ISSUE TITLE
请问glm edge为什么不采用glm4的结构，是基于推理硬件友好考虑，还是效果上的考虑？

### ISSUE THREAD

**Issue by enduringstack** [THUDM/GLM-Edge#6]
### Feature request  / 功能建议

请问glm edge为什么不采用glm4的结构，是基于推理硬件友好考虑，还是效果上的考虑？

### Motivation / 动机

请问glm edge为什么不采用glm4的结构，是基于推理硬件友好考虑，还是效果上的考虑？

### Your contribution / 您的贡献

na

**Comment by zRzRzRzRzRzRzR** [comment]
结构上有一定的区别，但是差距不大，主要目的是在模型变小后还能保持一定的性能考虑

**Comment by enduringstack** [comment]
感谢回复。目前看到端侧是decode的结构了，而glm应该是encoder的结构，这两者在部署态他们的结构差异在哪里呢
@zRzRzRzRzRzRzR

**Comment by Sengxian** [comment]
主要是为了推理硬件适配友好的考虑

**Comment by zRzRzRzRzRzRzR** [comment]
> 感谢回复。目前看到端侧是decode的结构了，而glm应该是encoder的结构，这两者在部署态他们的结构差异在哪里呢? 另外请问高通部署使用genie sdk了吗？ @zRzRzRzRzRzRzR

开源的 GLM-Edge 以及 GLM-4-9B-Chat 模型是 decoder-only结构哈，可以自行查看模型文件中的modeling_chatglm.py
