### ISSUE TITLE
4b-chat有tools插件调用能力吗，如果具备能提供代码例子吗，谢谢

### ISSUE THREAD

**Issue by bjfk2006** [THUDM/GLM-Edge#9]
### Feature request  / 功能建议

4b-chat有tools插件调用能力吗，如果具备能提供代码例子吗，谢谢

### Motivation / 动机

4b-chat有tools插件调用能力吗，如果具备能提供代码例子吗，谢谢

### Your contribution / 您的贡献

4b-chat有tools插件调用能力吗，如果具备能提供代码例子吗，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型没有function call能力哦
